# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then call a random question with `pick()` an hint towards its solution with
`hint(n)` and the answer with `answer(n)`, where n is the number of the picked question.

In [4]:
%run initialise.py

In [5]:
pick()

14. Create a random vector of size 30 and find the mean value (★☆☆)


In [10]:
hint(14)

hint: mean


In [14]:
answer(14)

Z = np.random.random(30)
m = Z.mean()
print(m)


In [16]:
t = np.random.random(30)
print(t)

[7.31769773e-01 2.22392483e-03 3.17985481e-01 7.34434354e-01
 9.04097300e-01 7.00297930e-01 7.34326271e-01 2.56649276e-01
 6.26401532e-01 8.98614316e-01 1.46714421e-01 1.32639480e-02
 1.80489104e-02 6.02057418e-02 1.12098956e-04 2.44055675e-01
 1.23903575e-01 8.71943074e-01 5.26951330e-01 1.66360723e-01
 5.59381247e-02 6.80585676e-01 2.93505763e-01 2.78573715e-01
 5.89386311e-01 9.50288160e-01 6.50286096e-02 3.26546194e-01
 5.66094967e-01 9.72252719e-01]


In [17]:
t.mean()

0.4285519964940813

In [18]:
pick()

40. Create a random vector of size 10 and sort it (★★☆)


In [19]:
g = np.random.random(10)
g

array([0.54253531, 0.13481074, 0.45244361, 0.66435388, 0.64777346,
       0.94332014, 0.90919116, 0.23449123, 0.60055817, 0.61334171])

In [20]:
g.mean()

0.5742819419989926

In [21]:
hint(40)

hint: sort


In [25]:
g.sort()
g

array([0.13481074, 0.23449123, 0.45244361, 0.54253531, 0.60055817,
       0.61334171, 0.64777346, 0.66435388, 0.90919116, 0.94332014])

In [24]:
answer(40)

Z = np.random.random(10)
Z.sort()
print(Z)


In [28]:
pick()

3. Create a null vector of size 10 (★☆☆)


In [30]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [31]:
pick()

91. How to create a record array from a regular array? (★★★)


In [32]:
hint(91)

hint: np.core.records.fromarrays


In [33]:
answer(91)

Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)


In [34]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [35]:
type(R)

numpy.recarray

In [36]:
pick()

62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)


In [37]:
hint(62)

hint: np.nditer


In [39]:
answer(62)

A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])


In [46]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [53]:
C = np.arange(4).reshape(4,1)
D = np.arange(4).reshape(1,4)
it = np.nditer([C,D,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
